import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface InstallerRequest {
  appName: string;
  appUrl: string;
  targetOs: "windows" | "macos" | "linux";
  framework: "electron" | "tauri";
}

// ============ UTILITY FUNCTIONS ============

function isGitHubUrl(url: string): boolean {
  return url.includes("github.com/") && !url.includes("github.com/orgs") && !url.includes("github.com/settings");
}

function parseGitHubUrl(url: string): { owner: string; repo: string; cloneUrl: string } | null {
  // Patterns: github.com/owner/repo, github.com/owner/repo.git, github.com/owner/repo/tree/branch
  const match = url.match(/github\.com\/([^\/]+)\/([^\/\s#?]+)/);
  if (!match) return null;
  
  const owner = match[1];
  let repo = match[2].replace(/\.git$/, "").replace(/\/$/, "");
  // Remove anything after repo name like /tree/main
  repo = repo.split("/")[0];
  
  return {
    owner,
    repo,
    cloneUrl: `https://github.com/${owner}/${repo}.git`
  };
}

// ============ ELECTRON GENERATORS (URL mode - WebView) ============

function generateElectronWindowsWebView(appName: string, appUrl: string): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Electron Desktop App (WebView Mode)
REM Generated by Web2Desktop
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Electron)
echo   Modo: WebView (carrega URL diretamente)
echo ==========================================
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    echo Por favor, instale o Node.js de: https://nodejs.org/
    pause
    exit /b 1
)

echo [OK] Node.js encontrado

set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}
echo Criando diretorio: %APP_DIR%
if exist "%APP_DIR%" rmdir /s /q "%APP_DIR%"
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

echo [INFO] Criando package.json...
(
echo {
echo   "name": "${sanitizedName.toLowerCase()}",
echo   "version": "1.0.0",
echo   "main": "main.js",
echo   "scripts": {
echo     "start": "electron .",
echo     "build": "electron-builder --win"
echo   },
echo   "build": {
echo     "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
echo     "productName": "${appName}",
echo     "win": { "target": ["nsis", "portable"] }
echo   }
echo }
) > package.json

echo [INFO] Criando main.js...
(
echo const { app, BrowserWindow, Menu } = require^('electron'^);
echo function createWindow^(^) {
echo   const win = new BrowserWindow^({ width: 1280, height: 800, autoHideMenuBar: true }^);
echo   Menu.setApplicationMenu^(null^);
echo   win.loadURL^('${appUrl}'^);
echo }
echo app.whenReady^(^).then^(createWindow^);
echo app.on^('window-all-closed', ^(^) =^> { if ^(process.platform !== 'darwin'^) app.quit^(^); }^);
) > main.js

echo [INFO] Instalando dependencias...
call npm install electron electron-builder --save-dev

echo.
echo ==========================================
echo   INSTALACAO CONCLUIDA!
echo ==========================================
echo.
echo   Para EXECUTAR: npm start
echo   Para GERAR EXE: npm run build
echo   (EXE estara em: %APP_DIR%\\dist)
echo.

(echo @echo off
echo cd /d "%APP_DIR%"
echo npm start
) > "%USERPROFILE%\\Desktop\\Executar_${sanitizedName}.bat"

echo [OK] Atalho criado: Executar_${sanitizedName}.bat
pause
`;
}

// ============ ELECTRON GENERATORS (GitHub mode - Clone and Build) ============

function generateElectronWindowsGitHub(appName: string, github: { owner: string; repo: string; cloneUrl: string }): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Electron Desktop App (GitHub Source)
REM Generated by Web2Desktop
REM Repository: ${github.cloneUrl}
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Electron)
echo   Modo: Build from GitHub Source
echo ==========================================
echo.

REM Check Git
where git >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Git nao encontrado!
    echo Por favor, instale o Git de: https://git-scm.com/
    pause
    exit /b 1
)
echo [OK] Git encontrado

REM Check Node.js
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    echo Por favor, instale o Node.js de: https://nodejs.org/
    pause
    exit /b 1
)
echo [OK] Node.js encontrado

set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}
echo.
echo Criando diretorio: %APP_DIR%
if exist "%APP_DIR%" rmdir /s /q "%APP_DIR%"
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

echo.
echo [INFO] Clonando repositorio: ${github.cloneUrl}
git clone ${github.cloneUrl} source
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Falha ao clonar repositorio!
    pause
    exit /b 1
)
echo [OK] Repositorio clonado

cd source

echo.
echo [INFO] Instalando dependencias do projeto...
call npm install
if %ERRORLEVEL% NEQ 0 (
    echo [AVISO] npm install falhou, tentando com --legacy-peer-deps...
    call npm install --legacy-peer-deps
)

echo.
echo [INFO] Fazendo build do projeto...
call npm run build 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [INFO] Tentando scripts alternativos de build...
    call npm run build:prod 2>nul || call npm run dist 2>nul || call npm run generate 2>nul
)

cd ..

REM Determine the dist folder
set DIST_FOLDER=source\\dist
if exist "source\\build" set DIST_FOLDER=source\\build
if exist "source\\out" set DIST_FOLDER=source\\out
if exist "source\\.output\\public" set DIST_FOLDER=source\\.output\\public

echo [INFO] Pasta de build detectada: %DIST_FOLDER%

echo.
echo [INFO] Configurando Electron wrapper...

(
echo {
echo   "name": "${sanitizedName.toLowerCase()}",
echo   "version": "1.0.0",
echo   "main": "main.js",
echo   "scripts": {
echo     "start": "electron .",
echo     "build": "electron-builder --win"
echo   },
echo   "build": {
echo     "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
echo     "productName": "${appName}",
echo     "files": ["main.js", "app/**/*"],
echo     "win": { "target": ["nsis", "portable"] }
echo   }
echo }
) > package.json

REM Copy built files
echo [INFO] Copiando arquivos buildados...
mkdir app
xcopy /s /e /y "%DIST_FOLDER%\\*" "app\\" >nul 2>nul

(
echo const { app, BrowserWindow, Menu } = require^('electron'^);
echo const path = require^('path'^);
echo function createWindow^(^) {
echo   const win = new BrowserWindow^({ width: 1280, height: 800, autoHideMenuBar: true }^);
echo   Menu.setApplicationMenu^(null^);
echo   win.loadFile^(path.join^(__dirname, 'app', 'index.html'^)^);
echo }
echo app.whenReady^(^).then^(createWindow^);
echo app.on^('window-all-closed', ^(^) =^> { if ^(process.platform !== 'darwin'^) app.quit^(^); }^);
) > main.js

echo [INFO] Instalando Electron...
call npm install electron electron-builder --save-dev

echo.
echo ==========================================
echo   BUILD COMPLETO!
echo ==========================================
echo.
echo   Para EXECUTAR: npm start
echo   Para GERAR EXE: npm run build
echo   (EXE estara em: %APP_DIR%\\dist)
echo.

(echo @echo off
echo cd /d "%APP_DIR%"
echo npm start
) > "%USERPROFILE%\\Desktop\\Executar_${sanitizedName}.bat"

echo [OK] Atalho criado: Executar_${sanitizedName}.bat
pause
`;
}

function generateElectronUnixWebView(appName: string, appUrl: string, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  const buildCmd = isMac ? "electron-builder --mac" : "electron-builder --linux";
  
  return `#!/bin/bash
# ========================================
# ${appName} - Electron Desktop App (WebView Mode)
# Generated by Web2Desktop
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Electron)"
echo "  Modo: WebView (carrega URL diretamente)"
echo "=========================================="
echo ""

if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    exit 1
fi
echo "[OK] Node.js encontrado"

APP_DIR="$HOME/Desktop/${sanitizedName}"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

cat > package.json << 'EOF'
{
  "name": "${sanitizedName.toLowerCase()}",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "${buildCmd}"
  },
  "build": {
    "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
    "productName": "${appName}"
  }
}
EOF

cat > main.js << 'EOF'
const { app, BrowserWindow, Menu } = require('electron');
function createWindow() {
  const win = new BrowserWindow({ width: 1280, height: 800 });
  Menu.setApplicationMenu(null);
  win.loadURL('${appUrl}');
}
app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
EOF

npm install electron electron-builder --save-dev

echo ""
echo "INSTALACAO CONCLUIDA!"
echo "Para EXECUTAR: npm start"
echo "Para GERAR INSTALADOR: npm run build"
`;
}

function generateElectronUnixGitHub(appName: string, github: { owner: string; repo: string; cloneUrl: string }, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  const buildCmd = isMac ? "electron-builder --mac" : "electron-builder --linux";
  
  return `#!/bin/bash
# ========================================
# ${appName} - Electron Desktop App (GitHub Source)
# Generated by Web2Desktop
# Repository: ${github.cloneUrl}
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Electron)"
echo "  Modo: Build from GitHub Source"
echo "=========================================="
echo ""

if ! command -v git &> /dev/null; then
    echo "[ERRO] Git nao encontrado!"
    exit 1
fi
echo "[OK] Git encontrado"

if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    exit 1
fi
echo "[OK] Node.js encontrado"

APP_DIR="$HOME/Desktop/${sanitizedName}"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

echo "[INFO] Clonando repositorio..."
git clone ${github.cloneUrl} source
cd source

echo "[INFO] Instalando dependencias..."
npm install || npm install --legacy-peer-deps

echo "[INFO] Fazendo build..."
npm run build || npm run build:prod || npm run dist || true

cd ..

# Detect dist folder
DIST_FOLDER="source/dist"
[ -d "source/build" ] && DIST_FOLDER="source/build"
[ -d "source/out" ] && DIST_FOLDER="source/out"
[ -d "source/.output/public" ] && DIST_FOLDER="source/.output/public"

echo "[INFO] Pasta de build: $DIST_FOLDER"

cat > package.json << 'EOF'
{
  "name": "${sanitizedName.toLowerCase()}",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "${buildCmd}"
  },
  "build": {
    "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
    "productName": "${appName}",
    "files": ["main.js", "app/**/*"]
  }
}
EOF

mkdir -p app
cp -r "$DIST_FOLDER"/* app/ 2>/dev/null || true

cat > main.js << 'EOF'
const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
function createWindow() {
  const win = new BrowserWindow({ width: 1280, height: 800 });
  Menu.setApplicationMenu(null);
  win.loadFile(path.join(__dirname, 'app', 'index.html'));
}
app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
EOF

npm install electron electron-builder --save-dev

echo ""
echo "BUILD COMPLETO!"
echo "Para EXECUTAR: npm start"
echo "Para GERAR INSTALADOR: npm run build"
`;
}

// ============ TAURI GENERATORS (URL mode - WebView) ============

function generateTauriWindowsWebView(appName: string, appUrl: string): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Tauri Desktop App (WebView Mode)
REM Generated by Web2Desktop
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Tauri)
echo   Modo: WebView (carrega URL diretamente)
echo ==========================================
echo.

where rustc >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [AVISO] Rust nao encontrado! Instalando...
    powershell -Command "Invoke-WebRequest -Uri 'https://win.rustup.rs/x86_64' -OutFile '%TEMP%\\rustup-init.exe'"
    "%TEMP%\\rustup-init.exe" -y
    set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
)
echo [OK] Rust configurado

where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    pause
    exit /b 1
)
echo [OK] Node.js encontrado

set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}_tauri
if exist "%APP_DIR%" rmdir /s /q "%APP_DIR%"
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

mkdir src
(
echo ^<!DOCTYPE html^>
echo ^<html^>^<head^>^<meta charset="UTF-8"^>^</head^>
echo ^<body style="margin:0;padding:0;height:100vh;"^>
echo ^<iframe src="${appUrl}" style="width:100%%;height:100%%;border:none;"^>^</iframe^>
echo ^</body^>^</html^>
) > src\\index.html

(
echo { "name": "${sanitizedName.toLowerCase()}", "version": "1.0.0", "scripts": { "tauri": "tauri" } }
) > package.json

call npm install @tauri-apps/cli --save-dev
call npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

echo.
echo INSTALACAO CONCLUIDA!
echo Para EXECUTAR: npx tauri dev
echo Para GERAR MSI/EXE: npx tauri build
pause
`;
}

// ============ TAURI GENERATORS (GitHub mode - Clone and Build) ============

function generateTauriWindowsGitHub(appName: string, github: { owner: string; repo: string; cloneUrl: string }): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Tauri Desktop App (GitHub Source)
REM Generated by Web2Desktop
REM Repository: ${github.cloneUrl}
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Tauri)
echo   Modo: Build from GitHub Source
echo ==========================================
echo.

where git >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Git nao encontrado!
    pause
    exit /b 1
)
echo [OK] Git encontrado

where rustc >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [AVISO] Rust nao encontrado! Instalando...
    powershell -Command "Invoke-WebRequest -Uri 'https://win.rustup.rs/x86_64' -OutFile '%TEMP%\\rustup-init.exe'"
    "%TEMP%\\rustup-init.exe" -y
    set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
)
echo [OK] Rust configurado

where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    pause
    exit /b 1
)
echo [OK] Node.js encontrado

set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}_tauri
if exist "%APP_DIR%" rmdir /s /q "%APP_DIR%"
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

echo [INFO] Clonando repositorio...
git clone ${github.cloneUrl} source
cd source

echo [INFO] Instalando dependencias...
call npm install || call npm install --legacy-peer-deps

echo [INFO] Fazendo build...
call npm run build 2>nul || call npm run build:prod 2>nul || echo [INFO] Build nao encontrado

cd ..

set DIST_FOLDER=source\\dist
if exist "source\\build" set DIST_FOLDER=source\\build
if exist "source\\out" set DIST_FOLDER=source\\out

echo [INFO] Pasta de build: %DIST_FOLDER%

(
echo { "name": "${sanitizedName.toLowerCase()}", "version": "1.0.0", "scripts": { "tauri": "tauri" } }
) > package.json

mkdir src
xcopy /s /e /y "%DIST_FOLDER%\\*" "src\\" >nul 2>nul

call npm install @tauri-apps/cli --save-dev
call npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

echo.
echo BUILD COMPLETO!
echo Para EXECUTAR: npx tauri dev
echo Para GERAR MSI/EXE: npx tauri build
pause
`;
}

function generateTauriUnixWebView(appName: string, appUrl: string, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `#!/bin/bash
# ========================================
# ${appName} - Tauri Desktop App (WebView Mode)
# Generated by Web2Desktop
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Tauri)"
echo "  Modo: WebView"
echo "=========================================="
echo ""

if ! command -v rustc &> /dev/null; then
    echo "[INFO] Instalando Rust..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
fi
echo "[OK] Rust configurado"

if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    exit 1
fi

APP_DIR="$HOME/Desktop/${sanitizedName}_tauri"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

mkdir src
cat > src/index.html << 'EOF'
<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;height:100vh;">
<iframe src="${appUrl}" style="width:100%;height:100%;border:none;"></iframe>
</body></html>
EOF

echo '{"name":"${sanitizedName.toLowerCase()}","version":"1.0.0","scripts":{"tauri":"tauri"}}' > package.json

npm install @tauri-apps/cli --save-dev
npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

echo "INSTALACAO CONCLUIDA!"
echo "Para EXECUTAR: npx tauri dev"
echo "Para GERAR INSTALADOR: npx tauri build"
`;
}

function generateTauriUnixGitHub(appName: string, github: { owner: string; repo: string; cloneUrl: string }, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `#!/bin/bash
# ========================================
# ${appName} - Tauri Desktop App (GitHub Source)
# Generated by Web2Desktop
# Repository: ${github.cloneUrl}
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Tauri)"
echo "  Modo: Build from GitHub Source"
echo "=========================================="
echo ""

if ! command -v git &> /dev/null; then
    echo "[ERRO] Git nao encontrado!"
    exit 1
fi

if ! command -v rustc &> /dev/null; then
    echo "[INFO] Instalando Rust..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
fi

if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    exit 1
fi

APP_DIR="$HOME/Desktop/${sanitizedName}_tauri"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

echo "[INFO] Clonando repositorio..."
git clone ${github.cloneUrl} source
cd source
npm install || npm install --legacy-peer-deps
npm run build || npm run build:prod || true
cd ..

DIST_FOLDER="source/dist"
[ -d "source/build" ] && DIST_FOLDER="source/build"
[ -d "source/out" ] && DIST_FOLDER="source/out"

echo '{"name":"${sanitizedName.toLowerCase()}","version":"1.0.0","scripts":{"tauri":"tauri"}}' > package.json

mkdir -p src
cp -r "$DIST_FOLDER"/* src/ 2>/dev/null || true

npm install @tauri-apps/cli --save-dev
npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

echo "BUILD COMPLETO!"
echo "Para EXECUTAR: npx tauri dev"
echo "Para GERAR INSTALADOR: npx tauri build"
`;
}

// ============ MAIN HANDLER ============

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { appName, appUrl, targetOs, framework } = await req.json() as InstallerRequest;

    if (!appName || !appUrl || !targetOs || !framework) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const isGitHub = isGitHubUrl(appUrl);
    const github = isGitHub ? parseGitHubUrl(appUrl) : null;

    console.log(`Generating ${framework} installer for ${appName} (${targetOs})`);
    console.log(`Source type: ${isGitHub ? 'GitHub repository' : 'URL WebView'}`);
    if (github) console.log(`GitHub: ${github.owner}/${github.repo}`);

    let fileContent: string;
    let fileName: string;
    let contentType: string;

    const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");

    if (framework === "electron") {
      if (isGitHub && github) {
        // GitHub mode - clone and build
        switch (targetOs) {
          case "windows":
            fileContent = generateElectronWindowsGitHub(appName, github);
            fileName = `${sanitizedName}_Electron_GitHub_installer.bat`;
            contentType = "application/x-bat";
            break;
          case "macos":
            fileContent = generateElectronUnixGitHub(appName, github, true);
            fileName = `${sanitizedName}_Electron_GitHub_installer.command`;
            contentType = "application/x-sh";
            break;
          case "linux":
            fileContent = generateElectronUnixGitHub(appName, github, false);
            fileName = `${sanitizedName}_Electron_GitHub_installer.sh`;
            contentType = "application/x-sh";
            break;
          default:
            throw new Error("Invalid target OS");
        }
      } else {
        // URL mode - WebView
        switch (targetOs) {
          case "windows":
            fileContent = generateElectronWindowsWebView(appName, appUrl);
            fileName = `${sanitizedName}_Electron_installer.bat`;
            contentType = "application/x-bat";
            break;
          case "macos":
            fileContent = generateElectronUnixWebView(appName, appUrl, true);
            fileName = `${sanitizedName}_Electron_installer.command`;
            contentType = "application/x-sh";
            break;
          case "linux":
            fileContent = generateElectronUnixWebView(appName, appUrl, false);
            fileName = `${sanitizedName}_Electron_installer.sh`;
            contentType = "application/x-sh";
            break;
          default:
            throw new Error("Invalid target OS");
        }
      }
    } else {
      // Tauri
      if (isGitHub && github) {
        // GitHub mode - clone and build
        switch (targetOs) {
          case "windows":
            fileContent = generateTauriWindowsGitHub(appName, github);
            fileName = `${sanitizedName}_Tauri_GitHub_installer.bat`;
            contentType = "application/x-bat";
            break;
          case "macos":
            fileContent = generateTauriUnixGitHub(appName, github, true);
            fileName = `${sanitizedName}_Tauri_GitHub_installer.command`;
            contentType = "application/x-sh";
            break;
          case "linux":
            fileContent = generateTauriUnixGitHub(appName, github, false);
            fileName = `${sanitizedName}_Tauri_GitHub_installer.sh`;
            contentType = "application/x-sh";
            break;
          default:
            throw new Error("Invalid target OS");
        }
      } else {
        // URL mode - WebView
        switch (targetOs) {
          case "windows":
            fileContent = generateTauriWindowsWebView(appName, appUrl);
            fileName = `${sanitizedName}_Tauri_installer.bat`;
            contentType = "application/x-bat";
            break;
          case "macos":
            fileContent = generateTauriUnixWebView(appName, appUrl, true);
            fileName = `${sanitizedName}_Tauri_installer.command`;
            contentType = "application/x-sh";
            break;
          case "linux":
            fileContent = generateTauriUnixWebView(appName, appUrl, false);
            fileName = `${sanitizedName}_Tauri_installer.sh`;
            contentType = "application/x-sh";
            break;
          default:
            throw new Error("Invalid target OS");
        }
      }
    }

    return new Response(fileContent, {
      headers: {
        ...corsHeaders,
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (e) {
    console.error("generate-installer error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
