import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface InstallerRequest {
  appName: string;
  appUrl: string;
  targetOs: "windows" | "macos" | "linux";
  framework: "electron" | "tauri";
}

// Generate Windows batch script that creates an Electron app
function generateWindowsInstaller(appName: string, appUrl: string): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
REM ========================================
REM ${appName} - Desktop App Installer
REM Generated by Web2Desktop
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup
echo ==========================================
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Node.js not found!
    echo Please install Node.js from: https://nodejs.org/
    echo.
    pause
    exit /b 1
)

echo [OK] Node.js found

REM Create app directory
set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}
echo Creating app directory at: %APP_DIR%
mkdir "%APP_DIR%" 2>nul
cd /d "%APP_DIR%"

REM Initialize package.json
echo {"name":"${sanitizedName.toLowerCase()}","version":"1.0.0","main":"main.js","scripts":{"start":"electron ."}} > package.json

REM Create main.js
echo const { app, BrowserWindow } = require('electron'); > main.js
echo. >> main.js
echo function createWindow() { >> main.js
echo   const win = new BrowserWindow({ >> main.js
echo     width: 1280, >> main.js
echo     height: 800, >> main.js
echo     icon: 'icon.ico', >> main.js
echo     webPreferences: { nodeIntegration: false, contextIsolation: true } >> main.js
echo   }); >> main.js
echo   win.loadURL('${appUrl}'); >> main.js
echo   win.setMenuBarVisibility(false); >> main.js
echo } >> main.js
echo. >> main.js
echo app.whenReady().then(createWindow); >> main.js
echo app.on('window-all-closed', () =^> { if (process.platform !== 'darwin') app.quit(); }); >> main.js

echo.
echo [INFO] Installing Electron (this may take a few minutes)...
call npm install electron --save-dev

echo.
echo ==========================================
echo   Installation Complete!
echo ==========================================
echo.
echo To run your app:
echo   1. Open Command Prompt
echo   2. cd "%APP_DIR%"
echo   3. npm start
echo.
echo Or create a shortcut on your desktop!
echo.

REM Create a launcher batch file
echo @echo off > run_${sanitizedName}.bat
echo cd /d "%APP_DIR%" >> run_${sanitizedName}.bat
echo npm start >> run_${sanitizedName}.bat

echo [OK] Created launcher: run_${sanitizedName}.bat
echo.
pause
`;
}

// Generate macOS/Linux shell script
function generateUnixInstaller(appName: string, appUrl: string, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  const platform = isMac ? "macOS" : "Linux";
  
  return `#!/bin/bash
# ========================================
# ${appName} - Desktop App Installer
# Generated by Web2Desktop
# Platform: ${platform}
# ========================================

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup"
echo "=========================================="
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "[ERROR] Node.js not found!"
    echo "Please install Node.js from: https://nodejs.org/"
    echo ""
    exit 1
fi

echo "[OK] Node.js found"

# Create app directory
APP_DIR="$HOME/Desktop/${sanitizedName}"
echo "Creating app directory at: $APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# Initialize package.json
cat > package.json << 'EOF'
{
  "name": "${sanitizedName.toLowerCase()}",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  }
}
EOF

# Create main.js
cat > main.js << 'EOF'
const { app, BrowserWindow } = require('electron');

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true
    }
  });
  win.loadURL('${appUrl}');
  win.setMenuBarVisibility(false);
}

app.whenReady().then(createWindow);
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
EOF

echo ""
echo "[INFO] Installing Electron (this may take a few minutes)..."
npm install electron --save-dev

echo ""
echo "=========================================="
echo "  Installation Complete!"
echo "=========================================="
echo ""
echo "To run your app:"
echo "  1. Open Terminal"
echo "  2. cd \\"$APP_DIR\\""
echo "  3. npm start"
echo ""

# Create a launcher script
cat > run_app.sh << 'LAUNCHER'
#!/bin/bash
cd "$HOME/Desktop/${sanitizedName}"
npm start
LAUNCHER
chmod +x run_app.sh

echo "[OK] Created launcher: run_app.sh"
echo ""
`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { appName, appUrl, targetOs } = await req.json() as InstallerRequest;

    if (!appName || !appUrl || !targetOs) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Generating installer for ${appName} (${targetOs})`);

    let fileContent: string;
    let fileName: string;
    let contentType: string;

    switch (targetOs) {
      case "windows":
        fileContent = generateWindowsInstaller(appName, appUrl);
        fileName = `${appName.replace(/[^a-zA-Z0-9]/g, "_")}_installer.bat`;
        contentType = "application/x-bat";
        break;
      case "macos":
        fileContent = generateUnixInstaller(appName, appUrl, true);
        fileName = `${appName.replace(/[^a-zA-Z0-9]/g, "_")}_installer.command`;
        contentType = "application/x-sh";
        break;
      case "linux":
        fileContent = generateUnixInstaller(appName, appUrl, false);
        fileName = `${appName.replace(/[^a-zA-Z0-9]/g, "_")}_installer.sh`;
        contentType = "application/x-sh";
        break;
      default:
        return new Response(
          JSON.stringify({ error: "Invalid target OS" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
    }

    // Return the file as a downloadable response
    return new Response(fileContent, {
      headers: {
        ...corsHeaders,
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (e) {
    console.error("generate-installer error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
