import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface InstallerRequest {
  appName: string;
  appUrl: string;
  targetOs: "windows" | "macos" | "linux";
  framework: "electron" | "tauri";
}

// ============ ELECTRON GENERATORS ============

function generateElectronWindowsInstaller(appName: string, appUrl: string): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Electron Desktop App Installer
REM Generated by Web2Desktop
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Electron)
echo ==========================================
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    echo Por favor, instale o Node.js de: https://nodejs.org/
    echo.
    pause
    exit /b 1
)

echo [OK] Node.js encontrado
for /f "tokens=*" %%i in ('node -v') do echo     Versao: %%i

REM Create app directory
set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}
echo.
echo Criando diretorio do app em: %APP_DIR%
if exist "%APP_DIR%" (
    echo [INFO] Diretorio ja existe, limpando...
    rmdir /s /q "%APP_DIR%"
)
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

REM Initialize package.json with electron-builder
echo.
echo [INFO] Criando configuracao do projeto...
(
echo {
echo   "name": "${sanitizedName.toLowerCase()}",
echo   "version": "1.0.0",
echo   "main": "main.js",
echo   "author": "Web2Desktop",
echo   "description": "${appName} - Desktop Application",
echo   "scripts": {
echo     "start": "electron .",
echo     "build": "electron-builder --win",
echo     "build-portable": "electron-builder --win portable"
echo   },
echo   "build": {
echo     "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
echo     "productName": "${appName}",
echo     "win": {
echo       "target": ["nsis", "portable"],
echo       "icon": "icon.ico"
echo     },
echo     "nsis": {
echo       "oneClick": false,
echo       "allowToChangeInstallationDirectory": true
echo     }
echo   }
echo }
) > package.json

REM Create main.js
echo [INFO] Criando arquivo principal...
(
echo const { app, BrowserWindow, Menu } = require^('electron'^);
echo const path = require^('path'^);
echo.
echo function createWindow^(^) {
echo   const win = new BrowserWindow^({
echo     width: 1280,
echo     height: 800,
echo     icon: path.join^(__dirname, 'icon.ico'^),
echo     webPreferences: {
echo       nodeIntegration: false,
echo       contextIsolation: true
echo     },
echo     autoHideMenuBar: true
echo   }^);
echo.
echo   Menu.setApplicationMenu^(null^);
echo   win.loadURL^('${appUrl}'^);
echo }
echo.
echo app.whenReady^(^).then^(createWindow^);
echo.
echo app.on^('window-all-closed', ^(^) =^> {
echo   if ^(process.platform !== 'darwin'^) app.quit^(^);
echo }^);
echo.
echo app.on^('activate', ^(^) =^> {
echo   if ^(BrowserWindow.getAllWindows^(^).length === 0^) createWindow^(^);
echo }^);
) > main.js

echo.
echo [INFO] Instalando dependencias (isso pode levar alguns minutos)...
call npm install electron --save-dev
call npm install electron-builder --save-dev

echo.
echo ==========================================
echo   Instalacao Concluida!
echo ==========================================
echo.
echo Opcoes disponiveis:
echo.
echo   1. EXECUTAR O APP (modo desenvolvimento):
echo      cd "%APP_DIR%"
echo      npm start
echo.
echo   2. GERAR INSTALADOR .EXE:
echo      cd "%APP_DIR%"
echo      npm run build
echo      (O instalador estara em: %APP_DIR%\\dist)
echo.
echo   3. GERAR VERSAO PORTATIL:
echo      cd "%APP_DIR%"
echo      npm run build-portable
echo.

REM Create launcher batch file
(
echo @echo off
echo cd /d "%APP_DIR%"
echo npm start
) > "%USERPROFILE%\\Desktop\\Executar_${sanitizedName}.bat"

echo [OK] Criado atalho na area de trabalho: Executar_${sanitizedName}.bat
echo.
echo Deseja iniciar o aplicativo agora? (S/N)
set /p choice="> "
if /i "%choice%"=="S" (
    echo.
    echo Iniciando ${appName}...
    npm start
)
pause
`;
}

function generateElectronUnixInstaller(appName: string, appUrl: string, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  const platform = isMac ? "macOS" : "Linux";
  const buildCmd = isMac ? "electron-builder --mac" : "electron-builder --linux";
  
  return `#!/bin/bash
# ========================================
# ${appName} - Electron Desktop App Installer
# Generated by Web2Desktop
# Platform: ${platform}
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Electron)"
echo "=========================================="
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    echo "Por favor, instale o Node.js de: https://nodejs.org/"
    echo ""
    exit 1
fi

echo "[OK] Node.js encontrado"
echo "    Versao: $(node -v)"

# Create app directory
APP_DIR="$HOME/Desktop/${sanitizedName}"
echo ""
echo "Criando diretorio do app em: $APP_DIR"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# Initialize package.json
echo ""
echo "[INFO] Criando configuracao do projeto..."
cat > package.json << 'PKGJSON'
{
  "name": "${sanitizedName.toLowerCase()}",
  "version": "1.0.0",
  "main": "main.js",
  "author": "Web2Desktop",
  "description": "${appName} - Desktop Application",
  "scripts": {
    "start": "electron .",
    "build": "${buildCmd}"
  },
  "build": {
    "appId": "com.web2desktop.${sanitizedName.toLowerCase()}",
    "productName": "${appName}",
    ${isMac ? `"mac": {
      "target": ["dmg", "zip"],
      "icon": "icon.icns"
    }` : `"linux": {
      "target": ["AppImage", "deb"],
      "icon": "icon.png"
    }`}
  }
}
PKGJSON

# Create main.js
echo "[INFO] Criando arquivo principal..."
cat > main.js << 'MAINJS'
const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true
    }
  });

  Menu.setApplicationMenu(null);
  win.loadURL('${appUrl}');
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});
MAINJS

echo ""
echo "[INFO] Instalando dependencias (isso pode levar alguns minutos)..."
npm install electron --save-dev
npm install electron-builder --save-dev

echo ""
echo "=========================================="
echo "  Instalacao Concluida!"
echo "=========================================="
echo ""
echo "Opcoes disponiveis:"
echo ""
echo "  1. EXECUTAR O APP (modo desenvolvimento):"
echo "     cd \\"$APP_DIR\\""
echo "     npm start"
echo ""
echo "  2. GERAR INSTALADOR:"
echo "     cd \\"$APP_DIR\\""
echo "     npm run build"
echo "     (O instalador estara em: $APP_DIR/dist)"
echo ""

# Create launcher script
cat > "$HOME/Desktop/Executar_${sanitizedName}.sh" << 'LAUNCHER'
#!/bin/bash
cd "$HOME/Desktop/${sanitizedName}"
npm start
LAUNCHER
chmod +x "$HOME/Desktop/Executar_${sanitizedName}.sh"

echo "[OK] Criado atalho na area de trabalho: Executar_${sanitizedName}.sh"
echo ""
read -p "Deseja iniciar o aplicativo agora? (s/n): " choice
if [[ "$choice" =~ ^[Ss]$ ]]; then
    echo ""
    echo "Iniciando ${appName}..."
    npm start
fi
`;
}

// ============ TAURI GENERATORS ============

function generateTauriWindowsInstaller(appName: string, appUrl: string): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  
  return `@echo off
chcp 65001 >nul
REM ========================================
REM ${appName} - Tauri Desktop App Installer
REM Generated by Web2Desktop
REM ========================================

echo.
echo ==========================================
echo   ${appName} - Desktop App Setup (Tauri)
echo ==========================================
echo.
echo [INFO] Tauri gera apps mais leves e seguros!
echo.

REM Check if Rust is installed
where rustc >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [AVISO] Rust nao encontrado!
    echo.
    echo Tauri requer Rust. Deseja instalar automaticamente? (S/N)
    set /p installrust="> "
    if /i "%installrust%"=="S" (
        echo.
        echo [INFO] Baixando rustup-init.exe...
        powershell -Command "Invoke-WebRequest -Uri 'https://win.rustup.rs/x86_64' -OutFile '%TEMP%\\rustup-init.exe'"
        echo [INFO] Instalando Rust...
        "%TEMP%\\rustup-init.exe" -y
        set PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
        echo [OK] Rust instalado!
    ) else (
        echo Por favor, instale Rust de: https://rustup.rs/
        pause
        exit /b 1
    )
)

echo [OK] Rust encontrado

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERRO] Node.js nao encontrado!
    echo Por favor, instale o Node.js de: https://nodejs.org/
    pause
    exit /b 1
)

echo [OK] Node.js encontrado

REM Create app directory
set APP_DIR=%USERPROFILE%\\Desktop\\${sanitizedName}_tauri
echo.
echo Criando diretorio do app em: %APP_DIR%
if exist "%APP_DIR%" rmdir /s /q "%APP_DIR%"
mkdir "%APP_DIR%"
cd /d "%APP_DIR%"

REM Create basic HTML that redirects to the URL
mkdir src
(
echo ^<!DOCTYPE html^>
echo ^<html^>
echo ^<head^>
echo   ^<meta charset="UTF-8"^>
echo   ^<meta http-equiv="refresh" content="0;url=${appUrl}"^>
echo   ^<title^>${appName}^</title^>
echo   ^<style^>
echo     body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: #1a1a2e; color: white; }
echo   ^</style^>
echo ^</head^>
echo ^<body^>
echo   ^<p^>Carregando ${appName}...^</p^>
echo   ^<script^>window.location.href = '${appUrl}';^</script^>
echo ^</body^>
echo ^</html^>
) > src\\index.html

REM Create package.json
(
echo {
echo   "name": "${sanitizedName.toLowerCase()}",
echo   "version": "1.0.0",
echo   "scripts": {
echo     "tauri": "tauri"
echo   }
echo }
) > package.json

echo.
echo [INFO] Instalando Tauri CLI...
call npm install @tauri-apps/cli --save-dev

echo.
echo [INFO] Inicializando projeto Tauri...
call npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

REM Update tauri.conf.json for external URL
echo [INFO] Configurando para carregar URL externa...
powershell -Command "(Get-Content 'src-tauri\\tauri.conf.json') -replace '\"distDir\": \"../src\"', '\"distDir\": \"../src\", \"devUrl\": \"${appUrl}\"' | Set-Content 'src-tauri\\tauri.conf.json'"

echo.
echo ==========================================
echo   Configuracao Concluida!
echo ==========================================
echo.
echo Opcoes disponiveis:
echo.
echo   1. EXECUTAR O APP (modo desenvolvimento):
echo      cd "%APP_DIR%"
echo      npx tauri dev
echo.
echo   2. GERAR INSTALADOR .MSI / .EXE:
echo      cd "%APP_DIR%"
echo      npx tauri build
echo      (O instalador estara em: %APP_DIR%\\src-tauri\\target\\release\\bundle)
echo.

REM Create launcher
(
echo @echo off
echo cd /d "%APP_DIR%"
echo npx tauri dev
) > "%USERPROFILE%\\Desktop\\Executar_${sanitizedName}_Tauri.bat"

echo [OK] Criado atalho: Executar_${sanitizedName}_Tauri.bat
echo.
pause
`;
}

function generateTauriUnixInstaller(appName: string, appUrl: string, isMac: boolean): string {
  const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");
  const platform = isMac ? "macOS" : "Linux";
  
  return `#!/bin/bash
# ========================================
# ${appName} - Tauri Desktop App Installer
# Generated by Web2Desktop
# Platform: ${platform}
# ========================================

set -e

echo ""
echo "=========================================="
echo "  ${appName} - Desktop App Setup (Tauri)"
echo "=========================================="
echo ""
echo "[INFO] Tauri gera apps mais leves e seguros!"
echo ""

# Check if Rust is installed
if ! command -v rustc &> /dev/null; then
    echo "[AVISO] Rust nao encontrado!"
    echo ""
    read -p "Tauri requer Rust. Deseja instalar automaticamente? (s/n): " installrust
    if [[ "$installrust" =~ ^[Ss]$ ]]; then
        echo ""
        echo "[INFO] Instalando Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
        echo "[OK] Rust instalado!"
    else
        echo "Por favor, instale Rust de: https://rustup.rs/"
        exit 1
    fi
fi

echo "[OK] Rust encontrado"
echo "    Versao: $(rustc --version)"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "[ERRO] Node.js nao encontrado!"
    echo "Por favor, instale o Node.js de: https://nodejs.org/"
    exit 1
fi

echo "[OK] Node.js encontrado"
echo "    Versao: $(node -v)"

${!isMac ? `
# Linux-specific dependencies
echo ""
echo "[INFO] Verificando dependencias do sistema..."
if command -v apt-get &> /dev/null; then
    echo "[INFO] Instalando dependencias do Tauri para Linux..."
    sudo apt-get update
    sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
fi
` : ''}

# Create app directory
APP_DIR="$HOME/Desktop/${sanitizedName}_tauri"
echo ""
echo "Criando diretorio do app em: $APP_DIR"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# Create basic HTML
mkdir -p src
cat > src/index.html << 'INDEXHTML'
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content="0;url=${appUrl}">
  <title>${appName}</title>
  <style>
    body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: #1a1a2e; color: white; }
  </style>
</head>
<body>
  <p>Carregando ${appName}...</p>
  <script>window.location.href = '${appUrl}';</script>
</body>
</html>
INDEXHTML

# Create package.json
cat > package.json << 'PKGJSON'
{
  "name": "${sanitizedName.toLowerCase()}",
  "version": "1.0.0",
  "scripts": {
    "tauri": "tauri"
  }
}
PKGJSON

echo ""
echo "[INFO] Instalando Tauri CLI..."
npm install @tauri-apps/cli --save-dev

echo ""
echo "[INFO] Inicializando projeto Tauri..."
npx tauri init --app-name "${appName}" --window-title "${appName}" --dist-dir "../src" --dev-path "../src"

echo ""
echo "=========================================="
echo "  Configuracao Concluida!"
echo "=========================================="
echo ""
echo "Opcoes disponiveis:"
echo ""
echo "  1. EXECUTAR O APP (modo desenvolvimento):"
echo "     cd \\"$APP_DIR\\""
echo "     npx tauri dev"
echo ""
echo "  2. GERAR INSTALADOR:"
echo "     cd \\"$APP_DIR\\""
echo "     npx tauri build"
${isMac ? 'echo "     (Gera .dmg em: $APP_DIR/src-tauri/target/release/bundle/dmg)"' : 'echo "     (Gera .deb/.AppImage em: $APP_DIR/src-tauri/target/release/bundle)"'}
echo ""

# Create launcher
cat > "$HOME/Desktop/Executar_${sanitizedName}_Tauri.sh" << 'LAUNCHER'
#!/bin/bash
cd "$HOME/Desktop/${sanitizedName}_tauri"
npx tauri dev
LAUNCHER
chmod +x "$HOME/Desktop/Executar_${sanitizedName}_Tauri.sh"

echo "[OK] Criado atalho: Executar_${sanitizedName}_Tauri.sh"
echo ""
read -p "Deseja iniciar o aplicativo agora? (s/n): " choice
if [[ "$choice" =~ ^[Ss]$ ]]; then
    echo ""
    echo "Iniciando ${appName}..."
    npx tauri dev
fi
`;
}

// ============ MAIN HANDLER ============

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { appName, appUrl, targetOs, framework } = await req.json() as InstallerRequest;

    if (!appName || !appUrl || !targetOs || !framework) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Generating ${framework} installer for ${appName} (${targetOs})`);

    let fileContent: string;
    let fileName: string;
    let contentType: string;

    const sanitizedName = appName.replace(/[^a-zA-Z0-9]/g, "_");

    if (framework === "electron") {
      switch (targetOs) {
        case "windows":
          fileContent = generateElectronWindowsInstaller(appName, appUrl);
          fileName = `${sanitizedName}_Electron_installer.bat`;
          contentType = "application/x-bat";
          break;
        case "macos":
          fileContent = generateElectronUnixInstaller(appName, appUrl, true);
          fileName = `${sanitizedName}_Electron_installer.command`;
          contentType = "application/x-sh";
          break;
        case "linux":
          fileContent = generateElectronUnixInstaller(appName, appUrl, false);
          fileName = `${sanitizedName}_Electron_installer.sh`;
          contentType = "application/x-sh";
          break;
        default:
          throw new Error("Invalid target OS");
      }
    } else {
      // Tauri
      switch (targetOs) {
        case "windows":
          fileContent = generateTauriWindowsInstaller(appName, appUrl);
          fileName = `${sanitizedName}_Tauri_installer.bat`;
          contentType = "application/x-bat";
          break;
        case "macos":
          fileContent = generateTauriUnixInstaller(appName, appUrl, true);
          fileName = `${sanitizedName}_Tauri_installer.command`;
          contentType = "application/x-sh";
          break;
        case "linux":
          fileContent = generateTauriUnixInstaller(appName, appUrl, false);
          fileName = `${sanitizedName}_Tauri_installer.sh`;
          contentType = "application/x-sh";
          break;
        default:
          throw new Error("Invalid target OS");
      }
    }

    // Return the file as a downloadable response
    return new Response(fileContent, {
      headers: {
        ...corsHeaders,
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (e) {
    console.error("generate-installer error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
